// MCP 工具目录（与 canvas-agent/src/canvas/schemas.ts 保持同步的手工镜像）。
// 说明：canvas-agent 是独立的本地 Node 服务，web 端无法直接 import 其源码，
// 因此这里维护一份名称与描述清单，供「本地能力」面板展示与直调。
// 同步约定：在 canvas-agent 侧新增工具后，请在此处追加同名条目。

export const toolNames = [
    "site_navigate",
    "canvas_list_projects",
    "canvas_get_state",
    "canvas_get_selection",
    "canvas_export_snapshot",
    "canvas_apply_ops",
    "canvas_create_node",
    "canvas_create_attachment_nodes",
    "canvas_create_text_node",
    "canvas_create_text_nodes",
    "canvas_create_config_node",
    "canvas_create_image_prompt_flow",
    "canvas_create_generation_flow",
    "canvas_generate_text",
    "canvas_generate_image",
    "canvas_generate_video",
    "canvas_generate_audio",
    "canvas_update_node",
    "canvas_update_node_text",
    "canvas_move_nodes",
    "canvas_resize_node",
    "canvas_delete_nodes",
    "canvas_connect_nodes",
    "canvas_select_nodes",
    "canvas_set_viewport",
    "canvas_run_generation",
    "generation_get_status",
    "workbench_image_get_config",
    "workbench_image_generate",
    "workbench_video_get_config",
    "workbench_video_generate",
    "prompts_search",
    "assets_list",
    "assets_add",
    "workflows_apply_template",
    "editor_import_media",
    "sync_github_backup",
    "apimart_generate_video",
    "apimart_task_status",
    "depth_model_status",
    "depth_model_prefetch",
] as const;

export type McpToolName = (typeof toolNames)[number];

export const toolDescriptions: Record<McpToolName, string> = {
    site_navigate: "跳转网站页面（/canvas、/image、/video、/prompts、/assets、/editor、/workflows、/config）。",
    canvas_list_projects: "列出用户全部画布（分页 + 关键字搜索）。",
    canvas_get_state: "读取当前网页画布的节点、连线、选区和视口。",
    canvas_get_selection: "读取当前网页画布选中的节点。",
    canvas_export_snapshot: "导出当前画布快照，用于理解布局。",
    canvas_apply_ops: "批量操作当前网页画布（增删改节点、连线、视口、选区、触发生成）。",
    canvas_create_node: "创建任意类型节点：text、image、config、video、audio。",
    canvas_create_attachment_nodes: "把当前对话中用户上传的图片附件创建成画布图片节点。",
    canvas_create_text_node: "在当前画布创建单个文本节点。",
    canvas_create_text_nodes: "批量创建文本节点。",
    canvas_create_config_node: "创建生成配置节点，可指定模式与参数并立即生成。",
    canvas_create_image_prompt_flow: "创建提示词 + 图片生成配置节点并自动连线。",
    canvas_create_generation_flow: "创建通用生成流程（文案/生图/生视频/音频）。",
    canvas_generate_text: "创建文本生成流程并立即生成。",
    canvas_generate_image: "创建图片生成流程并立即生成。",
    canvas_generate_video: "创建视频生成流程并立即生成。",
    canvas_generate_audio: "创建音频生成流程并立即生成。",
    canvas_update_node: "更新节点基础字段或 metadata。",
    canvas_update_node_text: "更新文本节点内容和标题。",
    canvas_move_nodes: "移动一个或多个节点。",
    canvas_resize_node: "调整节点尺寸。",
    canvas_delete_nodes: "删除指定节点及相关连线。",
    canvas_connect_nodes: "批量连接节点。",
    canvas_select_nodes: "设置当前选中节点。",
    canvas_set_viewport: "调整画布视口。",
    canvas_run_generation: "触发指定节点生成。",
    generation_get_status: "查询生成任务状态（画布 + 工作台）。",
    workbench_image_get_config: "读取生图工作台当前参数与可选项。",
    workbench_image_generate: "在生图工作台生成图片。",
    workbench_video_get_config: "读取视频创作台当前参数与可选项。",
    workbench_video_generate: "在视频创作台生成视频。",
    prompts_search: "搜索提示词库。",
    assets_list: "列出「我的素材」。",
    assets_add: "向「我的素材」新增素材。",
    workflows_apply_template: "用预置验证过的画布工作流模板一键创建新画布工程（动作迁移/首尾帧/对口型/多机位分镜）。",
    editor_import_media: "把「我的资产」和/或画布项目素材导入 Timeline Studio 时间轴剪辑器。",
    sync_github_backup: "把画布工程（可选含素材）备份到用户配置的 GitHub 私有仓库。",
    apimart_generate_video: "用 APIMart 渠道提交异步视频生成任务，返回 taskId。",
    apimart_task_status: "查询 APIMart 异步任务状态与结果 URL。",
    depth_model_status: "查询深度提取模型（Depth-Anything-V2-Small）状态：WebGPU 可用性、本地缓存。可触发后台预下载。",
    depth_model_prefetch: "立即后台下载深度模型权重到浏览器本地缓存。",
};
